config {
    type: "view"
}
 with lastAgent as (
  select distinct ParentId,childId,
  last_value(AgentName) over(partition by parentid order by CallStartDateTime asc 
                            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)agentName,
                            
  last_value(AgentMobile) over(partition by parentid order by CallStartDateTime asc 
                            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)agentNumber
  from ${ref("calling")}
)
select parentid,childId,agentNumber,max(lastAgent.AgentName)AgentName
from lastAgent
group by parentId,childId,agentNumber
order by parentId asc