config {
    type:"table",
    tags: "wa_daily",
    schema: "whatsapp",
    uniqueKey: ["id" ,"uuid"],
    description: "Incoming message details of users on Bihar Onboarding and FLN Number",
    columns: {
        phone_number: "Phone number of user(parent)",
        id: "unique message id",
        uuid: "special standardized identifier for each message conversation to be unique across systems and time",
        chat_id: "Id of the chat (generated in the period of 24 hrs)",
        message_type:"type of message e.g., text, image, audio, document",
        message_content: "Content of incoming message",
        sent_at: "Date and time the message was sent by user(IST)",
        saajha_whatsapp_number: "Whatsapp bot number in which message was received here: 911171817073 ",
        wa_number_purpose: "Purpose for which that whatsapp number is used. 4 distinct values: bihar,agent,only fln,onboarding Here: Bihar",
        context_id:"Its a reference (when we quote or reply to a message). Help us to connect to any message"
    }
}

SELECT distinct 
    safe_cast(trim(from_addr,'""[]+') as int64) phone_number,
    id,
    uuid, 
    chat_id,
    message_type, 
    content message_content, 
    datetime_add(inserted_at, Interval 330 minute)sent_at,
    911171817073 saajha_whatsapp_number,
    "Bihar" wa_number_purpose,
    context_id,
from ${ref("911171817073","messages")}
inner join ${ref("std_bihar_profile")} b
on phone_number=safe_cast(trim(from_addr,'""[]+') as int64)

where 1=1 
-- b.phone_number is null 
and message_type not in ("interactive","button") and direction="inbound" 
and date(datetime_add(updated_at, Interval 330 minute))< current_date("Asia/Kolkata")
and date( datetime_add(inserted_at, Interval 330 minute))>='2025-04-01'
