config {
    type:"table"
}

select firstAss.*, lastAss.* except(childId),
case 
  when lastHindiAssessedDate>firstHindiAssessedDate and firstHindilevel<lastHindilevel then "Improved"
  when lastHindiAssessedDate>firstHindiAssessedDate and firstHindilevel=lastHindilevel then "Same"
  when lastHindiAssessedDate>firstHindiAssessedDate and firstHindilevel>lastHindilevel then "Declined"
  when lastHindiAssessedDate=firstHindiAssessedDate or firstHindiAssessedDate is null or LastHindiAssessedDate is null then "single_assessment"
end hindiImprovementStatus
from ${ref("valid_first_hindi_assess")} firstAss 
left join ${ref("valid_last_hindi_assess")} lastAss 
on firstAss.childId = lastAss.childId