config {
    type:"table"
}


with uniqueHindiAssDates as (select distinct
      childId,  
      DATE(AssessmentTakenOn)HindiAssessDate,
      from ${ref("hindiAssessment")}
      order by HindiAssessDate asc
      )
, HindiLagDates as (SELECT
      DISTINCT childId,
      HindiAssessDate,
      LAG(DATE(HindiAssessDate)) OVER (PARTITION BY childId ORDER BY HindiAssessDate ASC)HindiLagDate,
    FROM
      uniqueHindiAssDates
    ORDER BY
      childId ASC,
      HindiAssessDate ASC,
      HindiLagDate ASC)

  ,valid_hindi as (
    SELECT distinct
      *,
    IF
      (HindiLagDate IS NULL, 0,DATE_DIFF(HindiAssessDate,HindiLagDate,day)) HindidateDifference,
    FROM
      HindiLagDates
    WHERE
    IF
      (HindiLagDate IS NULL, 0,DATE_DIFF(HindiAssessDate,HindiLagDate,day))=0
  UNION ALL (
    SELECT
      *,
    IF
      (HindiLagDate IS NULL, 0,DATE_DIFF(HindiAssessDate,HindiLagDate,day)) HindidateDifference,
    FROM
      HindiLagDates
    WHERE
    IF
      (HindiLagDate IS NULL, 0,DATE_DIFF(HindiAssessDate,HindiLagDate,day))>=30
     ORDER BY
    childId DESC)
    )
select *, row_number() over(partition by childId order by hindiAssessDate asc)mathrounds
from valid_hindi
order by childId asc, mathrounds asc
    