config {
    type:"table"
}
with firstHindiAssTakenOn as(
  select distinct childId,min(assessmentTakenON)firstAssessmentTakenOn
  from ${ref("hindiAssessment")}
  group by childId
)
, firstHindiLevels as(
  select distinct fhd.*,date(fhd.firstAssessmentTakenOn)firsthindiAssessedDate,last_value(hindiLevel)over(partition by fhd.childId order by firstAssessmentTakenOn asc rows between unbounded preceding and unbounded following)  as firstHindiLevel
  from firsthindiAssTakenOn fhd
  inner join ${ref("hindi_levels")} hl
  on fhd.firstAssessmentTakenOn = hl.assessmentTakenOn and fhd.childId = hl.childId
)

  select lml.*
  from firsthindiLevels lml
  inner join ${ref("valid_hindi_assessment")} va
  on lml.childId=va.childId and lml.firsthindiAssessedDate= va.hindiAssessDate
