config {
    type: "table"
}

with uniqueMathAssDates as (select distinct
      childId,  
      DATE(AssessmentTakenOn)mathAssessDate,
      from ${ref("mathAssessment")}
      order by mathAssessDate asc
      )
, mathLagDates as (SELECT
      DISTINCT childId,
      mathAssessDate,
      LAG(DATE(mathAssessDate)) OVER (PARTITION BY childId ORDER BY mathAssessDate ASC)mathLagDate,
    FROM
      uniqueMathAssDates
    ORDER BY
      childId ASC,
      mathAssessDate ASC,
      mathLagDate ASC)

 
,valid_math as    (SELECT distinct
      *,
    IF
      (mathLagDate IS NULL, 0,DATE_DIFF(mathAssessDate,mathLagDate,day)) mathdateDifference,
    FROM
      mathLagDates
    WHERE
    IF
      (mathLagDate IS NULL, 0,DATE_DIFF(mathAssessDate,mathLagDate,day))=0
  UNION ALL (
    SELECT
      *,
    IF
      (mathLagDate IS NULL, 0,DATE_DIFF(mathAssessDate,mathLagDate,day)) mathdateDifference,
    FROM
      mathLagDates
    WHERE
    IF
      (mathLagDate IS NULL, 0,DATE_DIFF(mathAssessDate,mathLagDate,day))>=30
     ORDER BY
    childId DESC))
select *, row_number() over(partition by childId order by mathAssessDate asc)mathrounds
from valid_math
order by childId asc, mathrounds asc
    
