config {
    type:"table"
}
with lastHindiAssTakenOn as(
  select distinct childId,max(assessmentTakenON)lastAssessmentTakenOn
  from ${ref("hindiAssessment")}
  group by childId
)
, lastHindiLevels as(
  select distinct lhd.*,date(lhd.lastAssessmentTakenOn)lastHindiAssessedDate,last_value(hindiLevel)over(partition by lhd.childId order by lastAssessmentTakenOn asc rows between unbounded preceding and unbounded following)  as lastHindiLevel
  from lastHindiAssTakenOn lhd
  inner join ${ref("hindi_levels")} ml
  on lhd.lastAssessmentTakenOn = ml.assessmentTakenOn and lhd.childId = ml.childId
)

  select lhl.*
  from lastHindiLevels lhl
  inner join ${ref("valid_hindi_assessment")} va
  on lhl.childId=va.childId and lhl.lastHindiAssessedDate= va.HindiAssessDate
