config {
    type:"table",
    tags: "wa_daily"
}
select distinct
    safe_cast(trim(from_addr,"+") as int64) phone_number,
    id,
    uuid,
    chat_id,
    template_button_text,
    template_button_index,
    template_button_template_name,
    template_button_template_language,
    datetime_add(inserted_at, Interval 330 minute)responded_at 

from ${ref("messages")}
where message_type="button"