config {
    type: "view"
}

SELECT
  DISTINCT agentMobile,agentName,ProjectId,
  ParentId,
  childId,
  ParentMobile,
  CallstartDatetime,
  Feedbacktype,
  Feedbackreason
FROM
  ${ref("incoming")}
  where ParentId is not null and childId is not null
UNION DISTINCT
SELECT
  DISTINCT agentMobile,agentName,ProjectId,
  ParentId,
  childId,
  ParentMobile,
  CallstartDatetime,
  Feedbacktype,
  Feedbackreason
FROM
  ${ref("roster")}
  where Childid is not null
