config {
    type: "table"
}
 with lastAgent as (
  select distinct 
  ParentId,childId,
  last_value(AgentName) over(partition by parentid order by CallStartDateTime asc 
                            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)agentName,
                            
  last_value(AgentMobile) over(partition by parentid order by CallStartDateTime asc 
                            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)agentNumber
  from ${ref("calling")}
)
select 
distinct 
parentid,childId,
safe_Cast(concat("91",agentNumber) as int64)agent_number,max(lastAgent.AgentName)AgentName
from lastAgent
group by parentId,childId,agent_number
order by parentId asc