
config {
    type: "table",
    tags: "call_daily"
}
with future_roster as (select distinct safe_cast(concat("91",AgentMobile) as int64)agentMobile,Round,
count(distinct if(date(calldate)= current_date("Asia/Kolkata"),ParentId,null))today_scheduled_call,
count(distinct if(date(calldate)> current_date("Asia/Kolkata"),ParentId,null))day_aftertomorrow_and_future_calls,
count(distinct if(date(calldate)>= current_date("Asia/Kolkata"),ParentId,null))overallCallsFromTodayOnwards
from `platform_commons.futureRoster`
where date(ExtractionDate) = date_sub(current_date("Asia/Kolkata"), INTERVAL 1 day) and date(CallDate) >= current_date("Asia/Kolkata") AND ProjectId <> 1102996 and AgentName <>"Aashish" 
group by all)

,scheduled as (
    select safe_cast(concat("91",AgentMobile) as int64)agentMobile, max(AgentName)agentName,Round , count(distinct ParentId)parentsScheduled
from `platform_commons.roster`
where CallDate >="2025-04-01"
group by all
)
,opted_out as (select distinct count(o.parentId) parentsOptedOut,agentMobile,callingRound as  Round
from `dataform.opted_out`o
inner join `dataform.called` c
on o.parentid=c.parentid and date(last_opted_out) = date(CallstartDatetime)
where date(last_opted_out) between "2025-04-01" and "2026-03-31" 
group by all)

select *
from scheduled
left join future_roster
using(AgentMobile,round)
left join opted_out
using(AgentMobile,round)




 