
config {
    type: "table",
    tags: "call_daily"
}
with future_roster as (select distinct safe_cast(concat("91",AgentMobile) as int64)agentMobile,Round,
count(distinct if(date(calldate)= current_date("Asia/Kolkata"),ParentId,null))today_scheduled_call,
count(distinct if(date(calldate)> current_date("Asia/Kolkata"),ParentId,null))day_aftertomorrow_and_future_calls,
count(distinct if(date(calldate)>= current_date("Asia/Kolkata"),ParentId,null))overallCallsFromTodayOnwards
from `platform_commons.futureRoster`
where date(ExtractionDate) = date_sub(current_date("Asia/Kolkata"), INTERVAL 1 day) and date(CallDate) >= current_date("Asia/Kolkata") AND ProjectId <> 1102996 and AgentName <>"Aashish" 
group by all)

,scheduled as (
    select safe_cast(concat("91",AgentMobile) as int64)agentMobile, max(AgentName)agentName,Round , count(distinct ParentId)parentsScheduled
from `platform_commons.roster`
where CallDate >="2025-04-01"
group by all
)
,opted_out as (select distinct count(o.parentId) parentsOptedOut,agentMobile,callingRound as  Round
from `dataform.opted_out`o
inner join `dataform.called` c
on o.parentid=c.parentid and date(last_opted_out) = date(CallstartDatetime)
where date(last_opted_out) between "2025-04-01" and "2026-03-31" 
group by all)


-- with /
,opt_out_parents as (select distinct o.parentId,agentMobile,agentName,round 
from `dataform.opted_out`o
inner join `platform_commons.futureRoster` c
on o.parentid=c.parentid and date(last_opted_out) = calldate
where date(last_opted_out) between "2025-04-01" and "2026-03-31")

, overalldials as (select distinct agentMobile,parentid,callingRound,
count(distinct CallstartDatetime) overalltotalDials,
count(distinct date(CallstartDatetime))overall_number_of_days_called
from `dataform.called`
group by all)

, average_call_attempts_before_opt_out as (
    select agentMobile,callinground as round,
    avg(overalltotalDials)avg_calls_attempted_before_opted_out,
     avg(overall_number_of_days_called)avg_days_called_before_opted_out
    from overalldials
    group by all
)

-- select distinct *
-- from opt_out_2024_25
-- left join overalldials
-- using(parentid)
-- left join year2024_25
-- using(parentid)
select *
from scheduled
left join future_roster
using(AgentMobile,round)
left join opted_out
using(AgentMobile,round)
left join average_call_attempts_before_opt_out
using(AgentMobile,round)




 