

config {
    type: "table",
    tags: ["call_daily"],
    description: "unique parentids from april 2025 till march 31st 2026 whose one child has done at 3 assessment"
}




select distinct OnBoardedUserId as parentid,
--If(Projectid =1103912,'Impact Evaluation','Other Projects') AS project_name,
from ${ref("valid_Assessed_2025_2026")}
inner join ${ref("IE")}
on assesseeActorId = ieid
where mathrounds>=3 and ProjectId<>1103908 
and projectid<>1103935

