config {
    type: "table",
    tags: "call_daily"
}


SELECT
  SUM(hour)/SUM(workedDays) hoursPerDay
FROM (
  SELECT
    AgentMobile,
    COUNT(DISTINCT DATE(CallStartDateTime)) workedDays,
    ROUND((SUM(TIMESTAMP_DIFF(CallEndDateTime,CallStartDateTime,second)))/3600,3) hour
  FROM
    `platform_commons.roster`
  WHERE
    ProjectId <> 1103233
    AND CallStartDateTime < CallEndDateTime
    AND CallStartDateTime IS NOT NULL
    AND DATE(callstartDatetime) BETWEEN DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 6 DAY)
    AND DATE_SUB(CURRENT_DATE("Asia/Kolkata"),INTERVAL 1 DAY)
  GROUP BY
    agentMobile)