config {
    type: "table"
}

SELECT
  DISTINCT firstEnrolledOn,
  parent_phone_number,"main_number" number_type,
  firstEnrolledAgentNumber,
  FirstEnrollmentFlowType,
  enrolled_in,
from ${ref("bauEnrolls")}

 union distinct
 
 SELECT
  DISTINCT firstEnrolledOn,
  alternateNumber,"alternate_number" number_type,
  firstEnrolledAgentNumber,
  FirstEnrollmentFlowType,
  enrolled_in,
from ${ref("bauEnrolls")}
where alternateNumber is not null